# TCL File Generated by Component Editor 18.1
# Fri Apr 21 15:33:40 CEST 2023
# DO NOT MODIFY


# 
# avalon_bus_bridge_byteenable "avalon_bus_bridge_byteenable" v1.0
#  2023.04.21.15:33:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_bus_bridge_byteenable
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_bus_bridge_byteenable
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_bus_bridge_byteenable
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_bus_bridge_byteenable
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_bus_bridge_byteenable.vhd VHDL PATH ../src/IP_Qsys/avalon_bus_bridge_byteenable.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock hps_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset hps_reset reset Input 1


# 
# connection point hps_avl_bus
# 
add_interface hps_avl_bus avalon end
set_interface_property hps_avl_bus addressUnits WORDS
set_interface_property hps_avl_bus associatedClock clock
set_interface_property hps_avl_bus associatedReset reset
set_interface_property hps_avl_bus bitsPerSymbol 8
set_interface_property hps_avl_bus burstOnBurstBoundariesOnly false
set_interface_property hps_avl_bus burstcountUnits WORDS
set_interface_property hps_avl_bus explicitAddressSpan 0
set_interface_property hps_avl_bus holdTime 0
set_interface_property hps_avl_bus linewrapBursts false
set_interface_property hps_avl_bus maximumPendingReadTransactions 1
set_interface_property hps_avl_bus maximumPendingWriteTransactions 0
set_interface_property hps_avl_bus readLatency 0
set_interface_property hps_avl_bus readWaitTime 1
set_interface_property hps_avl_bus setupTime 0
set_interface_property hps_avl_bus timingUnits Cycles
set_interface_property hps_avl_bus writeWaitTime 0
set_interface_property hps_avl_bus ENABLED true
set_interface_property hps_avl_bus EXPORT_OF ""
set_interface_property hps_avl_bus PORT_NAME_MAP ""
set_interface_property hps_avl_bus CMSIS_SVD_VARIABLES ""
set_interface_property hps_avl_bus SVD_ADDRESS_GROUP ""

add_interface_port hps_avl_bus hps_address address Input 14
add_interface_port hps_avl_bus hps_byteenable byteenable Input 4
add_interface_port hps_avl_bus hps_write write Input 1
add_interface_port hps_avl_bus hps_writedata writedata Input 32
add_interface_port hps_avl_bus hps_read read Input 1
add_interface_port hps_avl_bus hps_readdatavalid readdatavalid Output 1
add_interface_port hps_avl_bus hps_readdata readdata Output 32
add_interface_port hps_avl_bus hps_waitrequest waitrequest Output 1
set_interface_assignment hps_avl_bus embeddedsw.configuration.isFlash 0
set_interface_assignment hps_avl_bus embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hps_avl_bus embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hps_avl_bus embeddedsw.configuration.isPrintableDevice 0


# 
# connection point logic_avl_export
# 
add_interface logic_avl_export conduit end
set_interface_property logic_avl_export associatedClock ""
set_interface_property logic_avl_export associatedReset ""
set_interface_property logic_avl_export ENABLED true
set_interface_property logic_avl_export EXPORT_OF ""
set_interface_property logic_avl_export PORT_NAME_MAP ""
set_interface_property logic_avl_export CMSIS_SVD_VARIABLES ""
set_interface_property logic_avl_export SVD_ADDRESS_GROUP ""

add_interface_port logic_avl_export logic_clk clk Output 1
add_interface_port logic_avl_export logic_reset reset Output 1
add_interface_port logic_avl_export logic_address address Output 14
add_interface_port logic_avl_export logic_byteenable byteenable Output 4
add_interface_port logic_avl_export logic_write write Output 1
add_interface_port logic_avl_export logic_writedata writedata Output 32
add_interface_port logic_avl_export logic_read read Output 1
add_interface_port logic_avl_export logic_readdatavalid readdatavalid Input 1
add_interface_port logic_avl_export logic_readdata readdata Input 32
add_interface_port logic_avl_export logic_waitrequest waitrequest Input 1

